apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 2368
  selector:
    app: ghost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.32.0
          # prettier-ignore
          env:
            - name: database__client
              value: sqlite3
            - name: database__connection__filename
              value: content/data/ghost.db
            - name: database__useNullAsDefault
              value: "true"
            - name: database__debug
              value: "false"
          ports:
            - containerPort: 2368
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: ghost.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ghost
                port:
                  number: 80
  tls:
    - secretName: ghost-tls
      hosts:
        - ghost.${DOMAIN}
