apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
          - name: POSTGRES_USER
            value: "thisshouldberandommaybe"
          - name: POSTGRES_PASSWORD
            value: "thisaswellandverylongandcomplicated"
          - name: POSTGRES_DB
            value: "mydatabase"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: my-postgres-longhorn-volume
          mountPath: /var/lib/ghost/content
      volumes:
      - name: my-postgres-longhorn-volume
        persistentVolumeClaim:
          claimName: postgres-longhorn-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
  - host: postgres.${DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: postgres
            port:
              number: 5432
