apiVersion: v1
kind: Service
metadata:
  name: system-info-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: system-info-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-info-web
spec:
  selector:
    matchLabels:
      app: system-info-web
  replicas: 1
  template:
    metadata:
      labels:
        app: system-info-web
    spec:
      containers:
      - name: system-info-web
        image: registry.${DOMAIN}/system-info-web
        ports:
        - containerPort: 8000
#      imagePullSecrets:
#      - name: secret-docker
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sysinfo-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: sysinfo.${DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: system-info-web
            port:
              number: 80
  tls:
    - secretName: system-info-web-tls
      hosts:
        - sysinfo.${DOMAIN}